# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141b512a7bd6ec357fc06c72d0b53bbde07eade782904d3878e997a582768c235c71c80b6aff922f02972fb13c7dede6167f62ccd6454674e91c6bbba379b832

test:
  secret_key_base: 16bf7cc006caaf91e57e9d32a965f076d39ea211be245589bad791ee96b729c17c40678023c5658f340636123a92bfdb61b266b22322ca6904ae28f7c4c28a9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
